apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: starboard
  namespace: argocd
spec:
  project: default
  source:
    chart: starboard-operator
    repoURL: https://aquasecurity.github.io/helm-charts/
    targetRevision: 0.9.1
    helm:
      values: |
        targetNamespaces: uipath
        trivy:
          ignoreUnfixed: true
  destination:
    server: https://kubernetes.default.svc
    namespace: cattle-logging-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true